version: '3.8'

services:
  web:
    build: .
    container_name: ci4-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Fuck_Off6769
      MYSQL_DATABASE: attendance
      MYSQL_USER: 
      MYSQL_PASSWORD: 
      TZ: "Asia/Kuala_Lumpur"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Fuck_Off6769
      UPLOAD_LIMIT: 64M
      MYSQL_DATABASE: attendance
      TZ: "Asia/Kuala_Lumpur"

volumes:
  db_data:
